Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Musica_MVC.Models;
using Musica_MVC.ViewModel;
using Musica_MVC.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.SignalR.Protocol;

namespace Musica_MVC.Controllers
{
    public class AlbumController : Controller
    {
        //public static List<Artista> artistas = Datos.Artistas;
        //public static List<Album> albumes = Datos.Albumes;

        public IActionResult Lista()
        {
            return View(Datos.Albumes);
        }

        public IActionResult ListaCanciones(int Id)
        {
            var album = Datos.Albumes.FirstOrDefault(a => a.IdAlbum == Id);
            var canciones = Datos.Canciones.Where(a => a.IdAlbum == Id).ToList();

            if(album == null || canciones == null)
            {
                return NotFound();
            }
            foreach (var cancion in canciones)
            {
                cancion.Album = album;
            }

            return View(canciones);
        }

        [HttpGet]
        public IActionResult Nuevo()
        {
            var viewModel = new AlbumViewModel()
            {
                AlbumVM = new Album(),
                Artistas = Datos.Artistas.Select(a => new SelectListItem
                {
                    Value = a.IdArtista.ToString(),
                    Text = a.Nombre
                }).ToList()
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Nuevo(AlbumViewModel viewModel)
        {
            var artista = Datos.Artistas.FirstOrDefault(a => a.IdArtista == viewModel.AlbumVM.IdArtista);
            if (artista != null)
            {
                viewModel.AlbumVM.Artista = artista;
            }

            viewModel.AlbumVM.IdAlbum = Datos.Albumes.Count > 0 ? Datos.Albumes.Max(a => a.IdAlbum) + 1 : 1;
            Datos.Albumes.Add(viewModel.AlbumVM);

            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public IActionResult Editar(int Id)
        {
            var album = Datos.Albumes.FirstOrDefault(a => a.IdAlbum == Id);
            if (album == null)
            {
                return NotFound();
            }
            var viewModel = new AlbumViewModel()
            {
                AlbumVM = album,
                Artistas = Datos.Artistas.Select(a => new SelectListItem
                {
                    Value = a.IdArtista.ToString(),
                    Text = a.Nombre
                }).ToList()
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Editar(AlbumViewModel viewModel)
        {
            var existente = Datos.Albumes.FirstOrDefault(a => a.IdAlbum == viewModel.AlbumVM.IdAlbum);
            var seleccionado = Datos.Artistas.FirstOrDefault(a => a.IdArtista == viewModel.AlbumVM.IdArtista);

            if (existente != null && seleccionado != null)
            {
                existente.Nombre = viewModel.AlbumVM.Nombre;
                existente.Artista = seleccionado;
            }

            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public IActionResult Eliminar(int Id)
        {
            var album = Datos.Albumes.FirstOrDefault(a => a.IdAlbum == Id);
            if (album == null)
            {
                return NotFound();
            }

            Datos.Canciones.RemoveAll(a => a.IdAlbum == Id);
            Datos.Albumes.Remove(album);

            return RedirectToAction(nameof(Lista));
        }
    }
}

Controllers/ArtistaController.cs
using Microsoft.AspNetCore.Mvc;
using Musica_MVC.Models;
using Musica_MVC.ViewModel;
using Musica_MVC.Data;
using System.Collections.Generic;
using System.Linq;

namespace Musica_MVC.Controllers
{
    public class ArtistaController : Controller
    {
        //private static List<Artista> artistas = Datos.Artistas;
        private static int id = 1;

        public IActionResult Lista()
        {
            return View(Datos.Artistas);
        }

        public IActionResult ListaAlbumes(int Id)
        {
            var artista = Datos.Artistas.FirstOrDefault(a => a.IdArtista == Id);
            var albumes = Datos.Albumes.Where(a => a.IdArtista == Id).ToList();
            if (artista == null || albumes == null)
            {
                return NotFound();
            }
            foreach(var album in albumes)
            {
                album.Artista = artista;
            }
            return View(albumes);
        }

        [HttpGet]
        public IActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Nuevo(Artista artista)
        {
            artista.IdArtista = id++;
            Datos.Artistas.Add(artista);

            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public IActionResult Editar(int Id)
        {
            var artista = Datos.Artistas.FirstOrDefault(a => a.IdArtista == Id);

            if (artista == null)
                return NotFound();

            return View(artista);
        }

        [HttpPost]
        public IActionResult Editar(Artista artista)
        {
            var existente = Datos.Artistas.FirstOrDefault(a => a.IdArtista == artista.IdArtista);
            if (existente != null)
            {
                existente.Nombre = artista.Nombre;
                existente.NombreCompleto = artista.NombreCompleto;
            }
            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public IActionResult Eliminar(int Id)
        {
            var artista = Datos.Artistas.FirstOrDefault(a => a.IdArtista == Id);
            var albumes = Datos.Albumes.Where(a => a.IdArtista == Id);

            if (artista == null || albumes == null)
            {
                return NotFound();
            }
            foreach (var album in albumes)
            {
                Datos.Canciones.RemoveAll(a => a.IdAlbum == album.IdAlbum);
            }
            Datos.Albumes.RemoveAll(a => a.IdArtista == Id);
            Datos.Artistas.Remove(artista);

            return RedirectToAction(nameof(Lista));
        }
    }
}

Controllers/CancionController.cs
using Microsoft.AspNetCore.Mvc;
using Musica_MVC.Models;
using Musica_MVC.ViewModel;
using Musica_MVC.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Musica_MVC.Controllers
{
    public class CancionController : Controller
    {
        //public static List<Album> albumes = Datos.Albumes;
        public IActionResult Lista()
        {
            return View(Datos.Canciones);
        }

        [HttpGet]
        public IActionResult Nuevo()
        {
            var viewModel = new CancionViewModel()
            {
                CancionVM = new Cancion(),
                Albumes = Datos.Albumes.Select(a => new SelectListItem
                {
                    Value = a.IdAlbum.ToString(),
                    Text = a.Nombre,
                }).ToList()
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Nuevo(CancionViewModel viewModel)
        {
            var album = Datos.Albumes.FirstOrDefault(a => a.IdAlbum == viewModel.CancionVM.IdAlbum);
            if (album != null)
            {
                viewModel.CancionVM.Album = album;
            }
            viewModel.CancionVM.IdCancion = Datos.Canciones.Count > 0 ? Datos.Canciones.Max(a => a.IdCancion) + 1 : 1;
            Datos.Canciones.Add(viewModel.CancionVM);

            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public IActionResult Editar(int Id)
        {
            var cancion = Datos.Canciones.FirstOrDefault(a => a.IdCancion == Id);
            if (cancion == null)
            {
                return NotFound();
            }
            var viewModel = new CancionViewModel()
            {
                CancionVM = cancion,
                Albumes = Datos.Albumes.Select(a => new SelectListItem
                {
                    Value = a.IdAlbum.ToString(),
                    Text = a.Nombre
                }).ToList()
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Editar(CancionViewModel viewModel)
        {
            var existente = Datos.Canciones.FirstOrDefault(a => a.IdCancion == viewModel.CancionVM.IdCancion);
            var seleccionado = Datos.Albumes.FirstOrDefault(a => a.IdAlbum == viewModel.CancionVM.IdAlbum);
            if (existente != null && seleccionado != null)
            {
                existente.Nombre = viewModel.CancionVM.Nombre;
                existente.Duracion = viewModel.CancionVM.Duracion;
                existente.Album = seleccionado;
            }

            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public IActionResult Eliminar(int Id)
        {
            var cancion = Datos.Canciones.FirstOrDefault(a => a.IdCancion == Id);
            if (cancion != null)
            {
                Datos.Canciones.Remove(cancion);
            }

            return RedirectToAction(nameof(Lista));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Musica MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Musica_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand uwu" asp-area="" asp-controller="Home" asp-action="Index">Musica MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artista" asp-action="Lista">Artistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Lista">Albumes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cancion" asp-action="Lista">Canciones</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        <div class="container">
            @RenderBody()
        </div>
    </main>
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Musica_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>